name: Build Validation

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-web:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
    
    - name: Build web app
      run: npm run build
    
    - name: Upload web build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: dist/
        retention-days: 1

  build-android:
    needs: build-web
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'
    
    - name: Check Java version
      run: java -version
    
    - name: Install dependencies
      run: npm ci
    
    - name: Download web build
      uses: actions/download-artifact@v4
      with:
        name: web-build
        path: dist/
    
    - name: Sync Capacitor
      run: |
        npx cap sync android
    
    - name: Build Android Debug APK
      working-directory: android
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 1
